export type HalfYearMetricStatus = "actual" | "plan" | "post-period";

export type HalfYearMetricTone = "positive" | "neutral" | "caution" | "negative" | "plan";

export type HalfYearMetric = {
  id: string;
  label: string;
  value: string;
  numericValue: number;
  unit: string;
  displayPeriod?: string;
  sourcePeriod?: string;
  comparison?: string;
  note?: string;
  status: HalfYearMetricStatus;
  tone: HalfYearMetricTone;
  sourcePages: readonly number[];
  materialPages: readonly number[];
};

export type GreenPlusFact = {
  id: string;
  label: string;
  value: string;
  numericValue: number;
  unit: string;
};

export type GreenPlusHighlight = {
  kind: "case" | "honor";
  label: string;
};

export type GreenPlusGroup = {
  id: "life-technology" | "commercial-operations" | "wellness" | "town-operations";
  label: string;
  summary: string;
  detail: string;
  status: "actual";
  sourcePeriod: "2026-H1";
  sourcePages: readonly number[];
  materialPages: readonly number[];
  facts: readonly GreenPlusFact[];
  highlights: readonly GreenPlusHighlight[];
};

export type SalesTrendBar = {
  label: string;
  value: number;
  direction: "positive" | "negative" | "zero";
  tone: "default" | "latest";
  topPct: number;
  heightPct: number;
};

export type SalesTrendModel = {
  zeroPct: number;
  bars: SalesTrendBar[];
};

function roundTrendPercent(value: number) {
  return Math.round(value * 10_000) / 10_000;
}

export function buildSalesTrendBars(monthlyValues: readonly number[]): SalesTrendModel {
  const values = monthlyValues.map((value) => Number.isFinite(value) ? value : 0);
  if (values.length === 0) return { zeroPct: 100, bars: [] };

  const maximum = Math.max(0, ...values);
  const minimum = Math.min(0, ...values);
  const range = maximum - minimum;
  const zeroPct = range === 0 ? 100 : roundTrendPercent(maximum / range * 100);

  return {
    zeroPct,
    bars: values.map((value, index) => {
      const valuePct = range === 0 ? zeroPct : roundTrendPercent((maximum - value) / range * 100);
      return {
        label: `${index + 1}月`,
        value,
        direction: value > 0 ? "positive" : value < 0 ? "negative" : "zero",
        tone: index === values.length - 1 ? "latest" : "default",
        topPct: value >= 0 ? valuePct : zeroPct,
        heightPct: range === 0 ? 0 : roundTrendPercent(Math.abs(value) / range * 100),
      };
    }),
  };
}

export const HALF_YEAR_2026_SOURCE = {
  title: "绿城中国1H2026业绩发布材料",
  period: "2026-H1",
  displayPeriod: "2026年1–6月",
  reportingDate: "2026-06-30",
  currency: "人民币",
  defaultMoneyUnit: "亿元",
  pageConvention: "PDF页码",
} as const;

export const HALF_YEAR_2026_GREEN_PLUS_GROUPS = [
  {
    id: "life-technology",
    label: "生活科技",
    summary: "品质与效率持续提升",
    detail: "高标打造绿城样板房、示范区，助力项目首开。",
    status: "actual",
    sourcePeriod: "2026-H1",
    sourcePages: [13],
    materialPages: [12],
    facts: [
      { id: "green-plus-life-showrooms", label: "样板房、示范区", value: "13", numericValue: 13, unit: "个" },
      { id: "green-plus-life-deliveries", label: "品质交付", value: "61", numericValue: 61, unit: "个项目" },
    ],
    highlights: [
      { kind: "case", label: "杭州晓风朗月｜在浙首个施工大总包项目·品质兑现" },
    ],
  },
  {
    id: "commercial-operations",
    label: "商用运营",
    summary: "轻资产运营与服务品质",
    detail: "杭州云集共享产业中心、上海北中环中心；地产背景酒管集团客户满意度 Top 1。",
    status: "actual",
    sourcePeriod: "2026-H1",
    sourcePages: [13],
    materialPages: [12],
    facts: [
      { id: "green-plus-commercial-projects", label: "轻资产运营项目", value: "2", numericValue: 2, unit: "个" },
      { id: "green-plus-commercial-streak", label: "服务品质连续蝉联", value: "18", numericValue: 18, unit: "个月" },
    ],
    highlights: [
      { kind: "case", label: "上海北中环中心｜长租公寓轻资产运营项目" },
    ],
  },
  {
    id: "wellness",
    label: "康养业务",
    summary: "规模创新高，运营能力增强",
    detail: "新拓项目位于衢州、台州、佛山。",
    status: "actual",
    sourcePeriod: "2026-H1",
    sourcePages: [13],
    materialPages: [12],
    facts: [
      { id: "green-plus-wellness-projects", label: "新拓咨询及委托运营", value: "5", numericValue: 5, unit: "个" },
      { id: "green-plus-wellness-beds", label: "累计管理床位", value: "1.4", numericValue: 1.4, unit: "万+" },
    ],
    highlights: [
      { kind: "honor", label: "入选“2026银发消费服务商 Top 50”" },
    ],
  },
  {
    id: "town-operations",
    label: "小镇运营",
    summary: "产业、会员、旅居与轻资产经营",
    detail: "覆盖五大产业，持续扩大会员、旅居产品、活动运营与轻资产拓展规模。",
    status: "actual",
    sourcePeriod: "2026-H1",
    sourcePages: [13],
    materialPages: [12],
    facts: [
      { id: "green-plus-town-industries", label: "五大产业", value: "商业、教育、文旅、康养、农业", numericValue: 5, unit: "" },
      { id: "green-plus-town-members", label: "绿城悦己宿集 · 会员数", value: "4万+", numericValue: 4, unit: "" },
      { id: "green-plus-town-first-year-sales", label: "旅居产品首年销量", value: "4万", numericValue: 4, unit: "套" },
      { id: "green-plus-town-exposure", label: "活动运营 · 年曝光量", value: "1亿+", numericValue: 1, unit: "" },
      { id: "green-plus-town-light-projects", label: "轻资产拓展 · 项目数", value: "9", numericValue: 9, unit: "个" },
      { id: "green-plus-town-honors", label: "行业认可 · 累计荣誉", value: "60+", numericValue: 60, unit: "项" },
    ],
    highlights: [
      { kind: "honor", label: "小镇IP运营获“产业综合运营优秀企业”" },
    ],
  },
] as const satisfies readonly GreenPlusGroup[];

export const HALF_YEAR_2026_HERO_METRICS = [
  {
    id: "h1-sales-operating",
    label: "操盘销售",
    value: "947",
    numericValue: 947,
    unit: "亿元",
    comparison: "行业 Top 4",
    note: "操盘口径，不与自投、权益销售相加",
    status: "actual",
    tone: "positive",
    sourcePages: [6],
    materialPages: [5],
  },
  {
    id: "h1-sales-self",
    label: "自投销售",
    value: "602",
    numericValue: 602,
    unit: "亿元",
    comparison: "行业 Top 6",
    note: "附录合计精确值 602.02 亿元",
    status: "actual",
    tone: "positive",
    sourcePages: [6, 29],
    materialPages: [5, 28],
  },
  {
    id: "h1-investment-new-value",
    label: "新增货值",
    value: "459",
    numericValue: 459,
    unit: "亿元",
    comparison: "行业 Top 4",
    note: "2026年1–6月实际",
    status: "actual",
    tone: "positive",
    sourcePages: [8],
    materialPages: [7],
  },
  {
    id: "h1-financial-revenue",
    label: "营业收入",
    value: "394.81",
    numericValue: 394.81,
    unit: "亿元",
    comparison: "同比 -26.0%",
    note: "合并财务口径",
    status: "actual",
    tone: "negative",
    sourcePages: [25],
    materialPages: [24],
  },
  {
    id: "h1-finance-cash",
    label: "货币资金",
    value: "619",
    numericValue: 619,
    unit: "亿元",
    comparison: "年末 632 亿元",
    note: "财务表精确值 618.65 亿元",
    status: "actual",
    tone: "neutral",
    sourcePages: [20, 26],
    materialPages: [19, 25],
  },
  {
    id: "h1-finance-average-cost",
    label: "平均融资成本",
    value: "3.2",
    numericValue: 3.2,
    unit: "%",
    comparison: "同比下降 40bps",
    note: "1H2025 为 3.6%",
    status: "actual",
    tone: "positive",
    sourcePages: [5, 21],
    materialPages: [4, 20],
  },
] as const satisfies readonly HalfYearMetric[];

export const HALF_YEAR_2026_SALES_METRICS = [
  {
    id: "h1-sales-equity",
    label: "权益销售",
    value: "407",
    numericValue: 407,
    unit: "亿元",
    comparison: "行业 Top 6",
    status: "actual",
    tone: "positive",
    sourcePages: [6],
    materialPages: [5],
  },
  {
    id: "h1-sales-collection-rate",
    label: "回款率",
    value: "101",
    numericValue: 101,
    unit: "%",
    comparison: "保持标杆水平",
    note: "材料未披露计算公式",
    status: "actual",
    tone: "positive",
    sourcePages: [6],
    materialPages: [5],
  },
  {
    id: "h1-sales-tier-one",
    label: "一线城市占比",
    value: "20",
    numericValue: 20,
    unit: "%",
    status: "actual",
    tone: "neutral",
    sourcePages: [6],
    materialPages: [5],
  },
  {
    id: "h1-sales-tier-two",
    label: "二线城市占比",
    value: "63",
    numericValue: 63,
    unit: "%",
    status: "actual",
    tone: "positive",
    sourcePages: [6],
    materialPages: [5],
  },
  {
    id: "h1-sales-tier-lower",
    label: "三四线城市占比",
    value: "17",
    numericValue: 17,
    unit: "%",
    status: "actual",
    tone: "neutral",
    sourcePages: [6],
    materialPages: [5],
  },
  {
    id: "h1-inventory-old-sales",
    label: "2021年及以前库存去化",
    value: "97.7",
    numericValue: 97.7,
    unit: "亿元",
    comparison: "年度目标 180 亿元",
    status: "actual",
    tone: "positive",
    sourcePages: [7],
    materialPages: [6],
  },
  {
    id: "h1-inventory-old-progress",
    label: "老库存去化目标进度",
    value: "54",
    numericValue: 54,
    unit: "%",
    status: "actual",
    tone: "neutral",
    sourcePages: [7],
    materialPages: [6],
  },
  {
    id: "h1-inventory-unsold-value",
    label: "总未售货值",
    value: "2,200+",
    numericValue: 2200,
    unit: "亿元",
    comparison: "截至6月30日",
    status: "actual",
    tone: "caution",
    sourcePages: [7],
    materialPages: [6],
  },
] as const satisfies readonly HalfYearMetric[];

export const HALF_YEAR_2026_INVESTMENT_METRICS = [
  {
    id: "h1-investment-projects",
    label: "新增项目",
    value: "22",
    numericValue: 22,
    unit: "宗",
    status: "actual",
    tone: "positive",
    sourcePages: [8, 30, 31],
    materialPages: [7, 29, 30],
  },
  {
    id: "h1-investment-saleable-area",
    label: "新增可售面积",
    value: "115",
    numericValue: 115,
    unit: "万㎡",
    note: "附录精确值 115.3167 万㎡，不含地下车储",
    status: "actual",
    tone: "neutral",
    sourcePages: [8, 30, 31],
    materialPages: [7, 29, 30],
  },
  {
    id: "h1-investment-equity-land-cost",
    label: "权益土地款",
    value: "186",
    numericValue: 186,
    unit: "亿元",
    comparison: "行业 Top 5",
    note: "附录精确承担金额 185.65 亿元",
    status: "actual",
    tone: "positive",
    sourcePages: [8, 30, 31],
    materialPages: [7, 29, 30],
  },
  {
    id: "h1-investment-equity-ratio",
    label: "新增投资权益比",
    value: "81",
    numericValue: 81,
    unit: "%",
    comparison: "较2025年 +12pts",
    status: "actual",
    tone: "positive",
    sourcePages: [8],
    materialPages: [7],
  },
  {
    id: "h1-investment-tier12-share",
    label: "一二线新增货值占比",
    value: "94",
    numericValue: 94,
    unit: "%",
    comparison: "同比 +6pts",
    status: "actual",
    tone: "positive",
    sourcePages: [8],
    materialPages: [7],
  },
  {
    id: "h1-investment-core-city-value",
    label: "北上杭新增货值",
    value: "324",
    numericValue: 324,
    unit: "亿元",
    comparison: "占比 71%",
    status: "actual",
    tone: "positive",
    sourcePages: [8],
    materialPages: [7],
  },
  {
    id: "h1-landbank-value",
    label: "土储总货值",
    value: "3,846",
    numericValue: 3846,
    unit: "亿元",
    comparison: "截至6月30日",
    status: "actual",
    tone: "neutral",
    sourcePages: [9],
    materialPages: [8],
  },
  {
    id: "h1-landbank-total-gfa",
    label: "总建筑面积",
    value: "2,289",
    numericValue: 2289,
    unit: "万㎡",
    status: "actual",
    tone: "neutral",
    sourcePages: [9, 32],
    materialPages: [8, 31],
  },
  {
    id: "h1-landbank-equity-gfa",
    label: "权益建筑面积",
    value: "1,434",
    numericValue: 1434,
    unit: "万㎡",
    status: "actual",
    tone: "neutral",
    sourcePages: [9],
    materialPages: [8],
  },
  {
    id: "h1-landbank-saleable-gfa",
    label: "总可售建筑面积",
    value: "1,517",
    numericValue: 1517,
    unit: "万㎡",
    note: "不含地下车储",
    status: "actual",
    tone: "neutral",
    sourcePages: [9, 32],
    materialPages: [8, 31],
  },
  {
    id: "h1-landbank-equity-saleable-gfa",
    label: "权益可售建筑面积",
    value: "927",
    numericValue: 927,
    unit: "万㎡",
    note: "不含地下车储",
    status: "actual",
    tone: "neutral",
    sourcePages: [9],
    materialPages: [8],
  },
] as const satisfies readonly HalfYearMetric[];

export const HALF_YEAR_2026_LIQUIDITY_METRICS = [
  {
    id: "h1-finance-available-cash",
    label: "可用资金",
    value: "348",
    numericValue: 348,
    unit: "亿元",
    status: "actual",
    tone: "positive",
    sourcePages: [20],
    materialPages: [19],
  },
  {
    id: "h1-finance-restricted-cash",
    label: "预售监管及受限资金",
    value: "271",
    numericValue: 271,
    unit: "亿元",
    status: "actual",
    tone: "neutral",
    sourcePages: [20],
    materialPages: [19],
  },
  {
    id: "h1-finance-cash-short-debt-ratio",
    label: "现金短债比",
    value: "2.0",
    numericValue: 2,
    unit: "倍",
    comparison: "2025年末 2.6倍",
    status: "actual",
    tone: "neutral",
    sourcePages: [20],
    materialPages: [19],
  },
  {
    id: "h1-finance-interest-bearing-debt",
    label: "有息负债",
    value: "1,308",
    numericValue: 1308,
    unit: "亿元",
    comparison: "年末 1,334 亿元",
    note: "财务表精确值 1,308.33 亿元",
    status: "actual",
    tone: "positive",
    sourcePages: [21, 27],
    materialPages: [20, 26],
  },
  {
    id: "h1-finance-debt-within-year",
    label: "一年内到期",
    value: "303",
    numericValue: 303,
    unit: "亿元",
    comparison: "占比 23.2%",
    status: "actual",
    tone: "caution",
    sourcePages: [20, 21],
    materialPages: [19, 20],
  },
  {
    id: "h1-finance-debt-one-to-two",
    label: "1–2年到期",
    value: "508",
    numericValue: 508,
    unit: "亿元",
    status: "actual",
    tone: "neutral",
    sourcePages: [21],
    materialPages: [20],
  },
  {
    id: "h1-finance-debt-over-two",
    label: "2年以上到期",
    value: "497",
    numericValue: 497,
    unit: "亿元",
    status: "actual",
    tone: "positive",
    sourcePages: [21],
    materialPages: [20],
  },
  {
    id: "h1-finance-net-debt",
    label: "净负债",
    value: "689.68",
    numericValue: 689.68,
    unit: "亿元",
    comparison: "较年末 -1.7%",
    status: "actual",
    tone: "positive",
    sourcePages: [27],
    materialPages: [26],
  },
  {
    id: "h1-finance-net-gearing",
    label: "净资产负债率",
    value: "63.9",
    numericValue: 63.9,
    unit: "%",
    comparison: "较年末下降 2.5pts",
    status: "actual",
    tone: "positive",
    sourcePages: [27],
    materialPages: [26],
  },
] as const satisfies readonly HalfYearMetric[];

export const HALF_YEAR_2026_RESOURCE_METRICS = [
  {
    id: "h2-resource-saleable-value",
    label: "下半年自投可售货值",
    value: "1,256",
    numericValue: 1256,
    unit: "亿元",
    note: "不含2026年8月及以后新获取项目当年可推盘货值",
    status: "plan",
    tone: "plan",
    sourcePages: [17],
    materialPages: [16],
  },
  {
    id: "h2-resource-saleable-area",
    label: "下半年自投可售面积",
    value: "439",
    numericValue: 439,
    unit: "万㎡",
    status: "plan",
    tone: "plan",
    sourcePages: [17],
    materialPages: [16],
  },
  {
    id: "h2-resource-existing",
    label: "存量在售货值",
    value: "759",
    numericValue: 759,
    unit: "亿元",
    comparison: "占比 60%",
    status: "plan",
    tone: "plan",
    sourcePages: [17],
    materialPages: [16],
  },
  {
    id: "h2-resource-new-launch",
    label: "计划新推货值",
    value: "497",
    numericValue: 497,
    unit: "亿元",
    comparison: "占比 40%",
    status: "plan",
    tone: "plan",
    sourcePages: [17],
    materialPages: [16],
  },
  {
    id: "h2-resource-brand-new",
    label: "其中全新推盘",
    value: "280",
    numericValue: 280,
    unit: "亿元",
    status: "plan",
    tone: "plan",
    sourcePages: [17],
    materialPages: [16],
  },
  {
    id: "h2-resource-q3",
    label: "三季度计划新推",
    value: "176",
    numericValue: 176,
    unit: "亿元",
    comparison: "占比 35%",
    status: "plan",
    tone: "plan",
    sourcePages: [17],
    materialPages: [16],
  },
  {
    id: "h2-resource-q4",
    label: "四季度计划新推",
    value: "321",
    numericValue: 321,
    unit: "亿元",
    comparison: "占比 65%",
    status: "plan",
    tone: "plan",
    sourcePages: [17],
    materialPages: [16],
  },
  {
    id: "h2-resource-sold-unrecognized",
    label: "已售未结总额",
    value: "1,669",
    numericValue: 1669,
    unit: "亿元",
    status: "actual",
    tone: "neutral",
    sourcePages: [18],
    materialPages: [17],
  },
  {
    id: "h2-resource-equity-unrecognized",
    label: "已售未结权益金额",
    value: "1,051",
    numericValue: 1051,
    unit: "亿元",
    comparison: "权益比 63%",
    status: "actual",
    tone: "neutral",
    sourcePages: [18],
    materialPages: [17],
  },
  {
    id: "h2-recognition-2026-total",
    label: "2H2026预计结转",
    value: "749",
    numericValue: 749,
    unit: "亿元",
    comparison: "权益 515亿元",
    status: "plan",
    tone: "plan",
    sourcePages: [18],
    materialPages: [17],
  },
  {
    id: "h2-recognition-2027-total",
    label: "2027预计结转",
    value: "877",
    numericValue: 877,
    unit: "亿元",
    comparison: "权益 518亿元",
    status: "plan",
    tone: "plan",
    sourcePages: [18],
    materialPages: [17],
  },
  {
    id: "h2-recognition-2028-total",
    label: "2028及以后预计结转",
    value: "43",
    numericValue: 43,
    unit: "亿元",
    comparison: "权益 18亿元",
    status: "plan",
    tone: "plan",
    sourcePages: [18],
    materialPages: [17],
  },
] as const satisfies readonly HalfYearMetric[];

export const HALF_YEAR_2026_EARNINGS_METRICS = [
  {
    id: "h1-financial-gross-profit",
    label: "毛利",
    value: "43.88",
    numericValue: 43.88,
    unit: "亿元",
    comparison: "同比 -38.7%",
    status: "actual",
    tone: "negative",
    sourcePages: [25],
    materialPages: [24],
  },
  {
    id: "h1-financial-net-profit",
    label: "净利润",
    value: "0.89",
    numericValue: 0.89,
    unit: "亿元",
    comparison: "同比 -92.7%",
    status: "actual",
    tone: "negative",
    sourcePages: [25],
    materialPages: [24],
  },
  {
    id: "h1-financial-attributable-profit",
    label: "归母利润",
    value: "0.82",
    numericValue: 0.82,
    unit: "亿元",
    comparison: "同比 -61.0%",
    status: "actual",
    tone: "negative",
    sourcePages: [25],
    materialPages: [24],
  },
  {
    id: "h1-cost-administrative",
    label: "行政开支",
    value: "12.15",
    numericValue: 12.15,
    unit: "亿元",
    comparison: "同比下降 20.2%",
    status: "actual",
    tone: "positive",
    sourcePages: [24, 25],
    materialPages: [23, 24],
  },
  {
    id: "h1-cost-marketing",
    label: "营销开支",
    value: "10.51",
    numericValue: 10.51,
    unit: "亿元",
    comparison: "同比下降 0.6%",
    status: "actual",
    tone: "neutral",
    sourcePages: [24, 25],
    materialPages: [23, 24],
  },
  {
    id: "h1-cost-finance",
    label: "财务费用",
    value: "11.38",
    numericValue: 11.38,
    unit: "亿元",
    comparison: "同比下降 0.3%",
    status: "actual",
    tone: "neutral",
    sourcePages: [25],
    materialPages: [24],
  },
] as const satisfies readonly HalfYearMetric[];

export const HALF_YEAR_2026_QUALITY_METRICS = [
  {
    id: "h1-managed-revenue",
    label: "代建收入",
    value: "14.66",
    numericValue: 14.66,
    unit: "亿元",
    comparison: "同比 +7%",
    status: "actual",
    tone: "positive",
    sourcePages: [12],
    materialPages: [11],
  },
  {
    id: "h1-managed-profit",
    label: "代建归母净利润",
    value: "2.71",
    numericValue: 2.71,
    unit: "亿元",
    comparison: "同比 +6%",
    status: "actual",
    tone: "positive",
    sourcePages: [12],
    materialPages: [11],
  },
  {
    id: "h1-managed-new-area",
    label: "代建新拓面积",
    value: "1,352",
    numericValue: 1352,
    unit: "万㎡",
    comparison: "行业 Top 1",
    status: "actual",
    tone: "positive",
    sourcePages: [12],
    materialPages: [11],
  },
  {
    id: "h1-managed-delivery-area",
    label: "代建交付面积",
    value: "545.6",
    numericValue: 545.6,
    unit: "万㎡",
    comparison: "超2.7万套 · Top 1",
    status: "actual",
    tone: "positive",
    sourcePages: [12],
    materialPages: [11],
  },
  {
    id: "h1-customer-satisfaction",
    label: "总体满意度",
    value: "93.3",
    numericValue: 93.3,
    unit: "分",
    comparison: "16城 Top 1",
    note: "普睿数智；Top 10均值89.9，行业均值71.5",
    status: "actual",
    tone: "positive",
    sourcePages: [14],
    materialPages: [13],
  },
  {
    id: "h1-customer-loyalty",
    label: "总体忠诚度",
    value: "89.1",
    numericValue: 89.1,
    unit: "%",
    comparison: "12城 Top 1",
    note: "普睿数智；Top 10均值77.8%，行业均值52.1%",
    status: "actual",
    tone: "positive",
    sourcePages: [14],
    materialPages: [13],
  },
  {
    id: "h1-delivery-projects",
    label: "自投及代建交付项目",
    value: "81",
    numericValue: 81,
    unit: "个",
    status: "actual",
    tone: "positive",
    sourcePages: [10],
    materialPages: [9],
  },
  {
    id: "h1-delivery-area",
    label: "自投及代建交付面积",
    value: "760",
    numericValue: 760,
    unit: "万㎡",
    comparison: "超3.7万户",
    status: "actual",
    tone: "positive",
    sourcePages: [10],
    materialPages: [9],
  },
] as const satisfies readonly HalfYearMetric[];

export const HALF_YEAR_2026_MANAGED_MARKET_SHARE_METRIC = {
  id: "managed-market-share",
  label: "市占率",
  value: "20.7",
  numericValue: 20.7,
  unit: "%",
  displayPeriod: "2025年度",
  sourcePeriod: "2025-FY",
  comparison: "2025年度",
  note: "市场份额连续十年超过20%",
  status: "actual",
  tone: "positive",
  sourcePages: [],
  materialPages: [],
} as const satisfies HalfYearMetric & { displayPeriod: string; sourcePeriod: string };

export const HALF_YEAR_2026_MANAGED_PERFORMANCE_METRICS = [
  {
    id: "managed-contract-total-area",
    label: "合约总面积",
    value: "12,000",
    numericValue: 12_000,
    unit: "万方",
    displayPeriod: "2026上半年",
    sourcePeriod: "2026-H1",
    comparison: "2026上半年",
    status: "actual",
    tone: "positive",
    sourcePages: [],
    materialPages: [],
  },
  {
    id: "managed-contract-construction-area",
    label: "合约在建面积",
    value: "4,490",
    numericValue: 4_490,
    unit: "万方",
    displayPeriod: "2026上半年",
    sourcePeriod: "2026-H1",
    comparison: "2026上半年",
    status: "actual",
    tone: "positive",
    sourcePages: [],
    materialPages: [],
  },
  {
    id: "managed-covered-cities",
    label: "覆盖城市",
    value: "132",
    numericValue: 132,
    unit: "座",
    displayPeriod: "2026上半年",
    sourcePeriod: "2026-H1",
    comparison: "2026上半年",
    status: "actual",
    tone: "positive",
    sourcePages: [],
    materialPages: [],
  },
  {
    id: "managed-new-contract-area",
    label: "新拓合约建面",
    value: "1,352",
    numericValue: 1_352,
    unit: "万方",
    displayPeriod: "2026上半年",
    sourcePeriod: "2026-H1",
    comparison: "2026上半年",
    status: "actual",
    tone: "positive",
    sourcePages: [],
    materialPages: [],
  },
  {
    id: "managed-sales-amount",
    label: "销售金额",
    value: "345",
    numericValue: 345,
    unit: "亿元",
    displayPeriod: "2026上半年",
    sourcePeriod: "2026-H1",
    comparison: "2026上半年",
    // note: "新房销售全行业 Top 11",
    status: "actual",
    tone: "positive",
    sourcePages: [],
    materialPages: [],
  },
  {
    id: "managed-delivery-performance-area",
    label: "交付面积",
    value: "546",
    numericValue: 546,
    unit: "万方",
    displayPeriod: "2026上半年",
    sourcePeriod: "2026-H1",
    comparison: "2026上半年",
    status: "actual",
    tone: "positive",
    sourcePages: [],
    materialPages: [],
  },
] as const satisfies readonly (HalfYearMetric & { displayPeriod: string; sourcePeriod: string })[];

export const HALF_YEAR_2026_POST_PERIOD_METRICS = [
  {
    id: "post-investment-new-value",
    label: "截至8月25日新增货值",
    value: "近640",
    numericValue: 640,
    unit: "亿元",
    comparison: "期后更新",
    note: "不得与1H2026实际459亿元混为同一时点",
    status: "post-period",
    tone: "caution",
    sourcePages: [8],
    materialPages: [7],
  },
  {
    id: "post-finance-cash-short-debt-ratio",
    label: "7月置换后现金短债比",
    value: "2.3",
    numericValue: 2.3,
    unit: "倍",
    comparison: "6月末 2.0倍",
    status: "post-period",
    tone: "positive",
    sourcePages: [20],
    materialPages: [19],
  },
  {
    id: "post-finance-debt-within-year-share",
    label: "7月置换后一年内到期占比",
    value: "20.3",
    numericValue: 20.3,
    unit: "%",
    comparison: "6月末 23.2%",
    status: "post-period",
    tone: "positive",
    sourcePages: [21],
    materialPages: [20],
  },
] as const satisfies readonly HalfYearMetric[];

export const HALF_YEAR_2026_ALL_METRICS = [
  ...HALF_YEAR_2026_HERO_METRICS,
  ...HALF_YEAR_2026_SALES_METRICS,
  ...HALF_YEAR_2026_INVESTMENT_METRICS,
  ...HALF_YEAR_2026_LIQUIDITY_METRICS,
  ...HALF_YEAR_2026_RESOURCE_METRICS,
  ...HALF_YEAR_2026_EARNINGS_METRICS,
  ...HALF_YEAR_2026_QUALITY_METRICS,
  ...HALF_YEAR_2026_POST_PERIOD_METRICS,
] as const satisfies readonly HalfYearMetric[];

export const HALF_YEAR_2026_METRIC_TOTALS = {
  total: HALF_YEAR_2026_ALL_METRICS.length,
  actual: HALF_YEAR_2026_ALL_METRICS.filter((metric) => metric.status === "actual").length,
  plan: HALF_YEAR_2026_ALL_METRICS.filter((metric) => metric.status === "plan").length,
  postPeriod: HALF_YEAR_2026_ALL_METRICS.filter((metric) => metric.status === "post-period").length,
} as const;
