export type WenshuProjectAttribute = {
  propertyTypes: string;
  greentownEquityRatio: number | null;
};
// Local-only, source-backed snapshot.
// Sources: dataset 1016 (project-level first-tier property types) and 3001 (Greentown ownership ratio).
export const WENSHU_PROJECT_ATTRIBUTES: Record<string, WenshuProjectAttribute> = {
  "P3605": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: null },
  "P3619": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3512": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3885": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3327": { propertyTypes: "车位储藏室", greentownEquityRatio: null },
  "P4115": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3291": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3614": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P4146": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3417": { propertyTypes: "车位储藏室", greentownEquityRatio: null },
  "P3600": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3495": { propertyTypes: "—", greentownEquityRatio: null },
  "P3297": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3583": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3790": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3464": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 15.6 },
  "P3504": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3673": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P4137": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3563": { propertyTypes: "车位储藏室", greentownEquityRatio: 45 },
  "P3545": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3847": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3400": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 100 },
  "P3664": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 50.5074 },
  "P3428": { propertyTypes: "车位储藏室", greentownEquityRatio: null },
  "P3581": { propertyTypes: "车位储藏室", greentownEquityRatio: 99.65 },
  "P3406": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 10 },
  "P3797": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3363": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3984": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3699": { propertyTypes: "—", greentownEquityRatio: 60 },
  "P4118": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3530": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3668": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3698": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3587": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: null },
  "P3629": { propertyTypes: "车位储藏室", greentownEquityRatio: null },
  "P3393": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: null },
  "P3621": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3333": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: 51.48 },
  "P3433": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 90.4 },
  "P3601": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 99.4689 },
  "P3750": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3607": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 100 },
  "P3331": { propertyTypes: "商办", greentownEquityRatio: null },
  "P3342": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: 85 },
  "P3362": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 41.7 },
  "P4125": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3349": { propertyTypes: "—", greentownEquityRatio: 100 },
  "P3346": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: 40 },
  "P3977": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3991": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3655": { propertyTypes: "—", greentownEquityRatio: 50 },
  "P3578": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P4064": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3564": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3536": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P4130": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3525": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3452": { propertyTypes: "商办", greentownEquityRatio: 85 },
  "P3505": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3594": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3306": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3837": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3895": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3688": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 16.7 },
  "P3329": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3360": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 31.92 },
  "P3378": { propertyTypes: "车位储藏室", greentownEquityRatio: null },
  "P4139": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3411": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3897": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P4091": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P4095": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3379": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3316": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3293": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3295": { propertyTypes: "住宅", greentownEquityRatio: 51 },
  "P3894": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3905": { propertyTypes: "住宅 / 商业 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3610": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: 70 },
  "P4096": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3821": { propertyTypes: "车位储藏室", greentownEquityRatio: null },
  "P4008": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3718": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3446": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: 97.9566 },
  "P3982": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3310": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: null },
  "P3627": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 31.71 },
  "P3485": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3646": { propertyTypes: "车位储藏室", greentownEquityRatio: null },
  "P3388": { propertyTypes: "车位储藏室", greentownEquityRatio: null },
  "P4003": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3549": { propertyTypes: "住宅 / 商办", greentownEquityRatio: 45 },
  "P4098": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3447": { propertyTypes: "住宅 / 商办", greentownEquityRatio: 61.9 },
  "P3731": { propertyTypes: "车位储藏室", greentownEquityRatio: null },
  "P3462": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3556": { propertyTypes: "—", greentownEquityRatio: 50 },
  "P3710": { propertyTypes: "—", greentownEquityRatio: 82.4622905 },
  "P3498": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 99.89 },
  "P3585": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: 42.63 },
  "P3786": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3483": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: null },
  "P3886": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3386": { propertyTypes: "—", greentownEquityRatio: null },
  "P3579": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P4105": { propertyTypes: "住宅", greentownEquityRatio: null },
  "P3700": { propertyTypes: "车位储藏室", greentownEquityRatio: null },
  "P3867": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3429": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3978": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P4006": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3377": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3559": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 85.66 },
  "P3499": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3807": { propertyTypes: "住宅 / 商办 / 车位储藏室 / 产业", greentownEquityRatio: null },
  "P3778": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 90 },
  "P3988": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3628": { propertyTypes: "—", greentownEquityRatio: 47.78 },
  "P3473": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3654": { propertyTypes: "商办", greentownEquityRatio: 50.7756 },
  "P3805": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3403": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: 70 },
  "P3825": { propertyTypes: "车位储藏室", greentownEquityRatio: null },
  "P4117": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3551": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: 97.56 },
  "P3880": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3875": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3598": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3470": { propertyTypes: "住宅", greentownEquityRatio: null },
  "P3616": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3364": { propertyTypes: "—", greentownEquityRatio: null },
  "P3744": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: null },
  "P3724": { propertyTypes: "车位储藏室", greentownEquityRatio: null },
  "P3883": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3719": { propertyTypes: "车位储藏室", greentownEquityRatio: null },
  "P3768": { propertyTypes: "住宅 / 商办", greentownEquityRatio: null },
  "P4108": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P4109": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3609": { propertyTypes: "—", greentownEquityRatio: null },
  "P3307": { propertyTypes: "车位储藏室", greentownEquityRatio: 36 },
  "P3300": { propertyTypes: "—", greentownEquityRatio: 20 },
  "P3906": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3882": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3806": { propertyTypes: "车位储藏室", greentownEquityRatio: null },
  "P4065": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3824": { propertyTypes: "车位储藏室", greentownEquityRatio: 100 },
  "P3856": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3841": { propertyTypes: "—", greentownEquityRatio: null },
  "P3555": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P4054": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3334": { propertyTypes: "车位储藏室", greentownEquityRatio: null },
  "P3693": { propertyTypes: "车位储藏室", greentownEquityRatio: null },
  "P3466": { propertyTypes: "车位储藏室", greentownEquityRatio: 50.37 },
  "P4106": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3423": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: null },
  "P3337": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3653": { propertyTypes: "车位储藏室", greentownEquityRatio: null },
  "P3416": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: null },
  "P3412": { propertyTypes: "车位储藏室", greentownEquityRatio: 57.357033 },
  "P3868": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3775": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3783": { propertyTypes: "住宅 / 车位储藏室 / 产业", greentownEquityRatio: null },
  "P4127": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3884": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3745": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3659": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P4076": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3599": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 33.27 },
  "P3820": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: null },
  "P3336": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: null },
  "P3987": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3729": { propertyTypes: "车位储藏室", greentownEquityRatio: null },
  "P3422": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: 24 },
  "P3301": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 98.66 },
  "P3793": { propertyTypes: "车位储藏室", greentownEquityRatio: null },
  "P3817": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3665": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 42.63 },
  "P3770": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3999": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3704": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: 45 },
  "P3756": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3703": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 96.0273 },
  "P3846": { propertyTypes: "—", greentownEquityRatio: null },
  "P4107": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3365": { propertyTypes: "车位储藏室", greentownEquityRatio: 49.5 },
  "P3461": { propertyTypes: "—", greentownEquityRatio: 100 },
  "P3874": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3622": { propertyTypes: "车位储藏室", greentownEquityRatio: null },
  "P3557": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 49.21 },
  "P3304": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: null },
  "P4004": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3857": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3408": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3392": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 99.82 },
  "P3613": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3572": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: null },
  "P3678": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3421": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 100 },
  "P3317": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 34.8 },
  "P3315": { propertyTypes: "—", greentownEquityRatio: 30 },
  "P3641": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 100 },
  "P3543": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3441": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3507": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3848": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3544": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3409": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: 100 },
  "P3420": { propertyTypes: "—", greentownEquityRatio: 45 },
  "P3979": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P4122": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3451": { propertyTypes: "—", greentownEquityRatio: 20 },
  "P3689": { propertyTypes: "—", greentownEquityRatio: 50 },
  "P3586": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3980": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3682": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 18.23 },
  "P3311": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 19.83 },
  "P3877": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3845": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P4110": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3516": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 56.43 },
  "P4014": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3741": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 100 },
  "P4047": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P4104": { propertyTypes: "住宅", greentownEquityRatio: null },
  "P3697": { propertyTypes: "车位储藏室", greentownEquityRatio: null },
  "P3424": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 54.4 },
  "P3985": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3706": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3475": { propertyTypes: "商办", greentownEquityRatio: null },
  "P4097": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3881": { propertyTypes: "住宅", greentownEquityRatio: null },
  "P3814": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3650": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 48.89 },
  "P3371": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 74.5 },
  "P4081": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3577": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 47.611032 },
  "P3666": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 40.801584 },
  "P3350": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3595": { propertyTypes: "车位储藏室", greentownEquityRatio: null },
  "P3514": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3376": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3792": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3802": { propertyTypes: "住宅", greentownEquityRatio: null },
  "P3458": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: null },
  "P3502": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P4090": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3795": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3889": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3637": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P4070": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3675": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3592": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3413": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3644": { propertyTypes: "—", greentownEquityRatio: 59.55 },
  "P3687": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 64.35 },
  "P3500": { propertyTypes: "车位储藏室", greentownEquityRatio: null },
  "P3708": { propertyTypes: "车位储藏室", greentownEquityRatio: null },
  "P3478": { propertyTypes: "住宅 / 商办", greentownEquityRatio: null },
  "P3658": { propertyTypes: "住宅", greentownEquityRatio: null },
  "P3542": { propertyTypes: "住宅", greentownEquityRatio: 50 },
  "P3611": { propertyTypes: "车位储藏室", greentownEquityRatio: null },
  "P4075": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3870": { propertyTypes: "住宅 / 车位储藏室 / 加装包", greentownEquityRatio: null },
  "P3515": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 98.000305 },
  "P3648": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 66.05 },
  "P3348": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3303": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3660": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 99.5 },
  "P3314": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 99.8448 },
  "P3352": { propertyTypes: "商办 / 车位储藏室 / 加装包", greentownEquityRatio: 49.52 },
  "P3487": { propertyTypes: "住宅 / 商办 / 车位储藏室 / 加装包", greentownEquityRatio: null },
  "P3480": { propertyTypes: "车位储藏室", greentownEquityRatio: 43.39 },
  "P3679": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 43.36 },
  "P3415": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 45.31 },
  "P3707": { propertyTypes: "车位储藏室", greentownEquityRatio: 99.09 },
  "P3353": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3391": { propertyTypes: "住宅 / 商办 / 车位储藏室 / 加装包", greentownEquityRatio: 50.7197 },
  "P3443": { propertyTypes: "住宅 / 商办 / 车位储藏室 / 加装包", greentownEquityRatio: null },
  "P3467": { propertyTypes: "车位储藏室", greentownEquityRatio: 48 },
  "P3580": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: null },
  "P3547": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: 99.7 },
  "P3383": { propertyTypes: "车位储藏室", greentownEquityRatio: 98.5417 },
  "P3395": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: 51 },
  "P3732": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P4001": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3389": { propertyTypes: "—", greentownEquityRatio: null },
  "P3832": { propertyTypes: "住宅 / 商办 / 车位储藏室 / 加装包", greentownEquityRatio: null },
  "P4123": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P4100": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3642": { propertyTypes: "车位储藏室", greentownEquityRatio: 51 },
  "P3437": { propertyTypes: "—", greentownEquityRatio: 46.95 },
  "P4101": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P4126": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3570": { propertyTypes: "商办", greentownEquityRatio: 51 },
  "P3527": { propertyTypes: "住宅 / 商办 / 车位储藏室 / 加装包", greentownEquityRatio: null },
  "P3397": { propertyTypes: "车位储藏室", greentownEquityRatio: 45.369 },
  "P3321": { propertyTypes: "商办 / 车位储藏室 / 产业", greentownEquityRatio: 54.93 },
  "P3449": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3751": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3626": { propertyTypes: "—", greentownEquityRatio: null },
  "P3465": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 51 },
  "P3681": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 43.37 },
  "P3375": { propertyTypes: "—", greentownEquityRatio: null },
  "P3322": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: null },
  "P3439": { propertyTypes: "住宅 / 商办", greentownEquityRatio: 100 },
  "P3554": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 47.49 },
  "P4074": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3779": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3860": { propertyTypes: "住宅 / 车位储藏室 / 加装包", greentownEquityRatio: null },
  "P3482": { propertyTypes: "—", greentownEquityRatio: 100 },
  "P3651": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3639": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 98.415 },
  "P4142": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3632": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3565": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: 40 },
  "P3662": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3548": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3625": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3398": { propertyTypes: "车位储藏室", greentownEquityRatio: null },
  "P3631": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 79.21 },
  "P3494": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3299": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P4132": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P4131": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3872": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P4082": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3789": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3481": { propertyTypes: "—", greentownEquityRatio: 50 },
  "P3713": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 27.14486346 },
  "P3513": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 51 },
  "P4147": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3788": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3726": { propertyTypes: "住宅 / 车位储藏室 / 加装包", greentownEquityRatio: null },
  "P3787": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3871": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P4007": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P4102": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3435": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: 37.5 },
  "P3769": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 100 },
  "P4138": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3680": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 32.21 },
  "P3798": { propertyTypes: "住宅", greentownEquityRatio: null },
  "P3553": { propertyTypes: "—", greentownEquityRatio: 90 },
  "P3696": { propertyTypes: "—", greentownEquityRatio: 90 },
  "P3325": { propertyTypes: "住宅 / 商办", greentownEquityRatio: 60 },
  "P4086": { propertyTypes: "住宅 / 商办", greentownEquityRatio: null },
  "P3459": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3535": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 100 },
  "P4148": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3474": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3591": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3419": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 93.41 },
  "P3764": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P4000": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3672": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 99.76 },
  "P3410": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3835": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P4080": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3683": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3623": { propertyTypes: "住宅 / 商办 / 车位储藏室 / 产业", greentownEquityRatio: null },
  "P3981": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3829": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3292": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3320": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 12.83 },
  "P3733": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3339": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P4145": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3645": { propertyTypes: "住宅 / 商办 / 公共配套 / 车位储藏室", greentownEquityRatio: null },
  "P3761": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3794": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3354": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3540": { propertyTypes: "—", greentownEquityRatio: 49 },
  "P4049": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3399": { propertyTypes: "—", greentownEquityRatio: 10 },
  "P3898": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P4011": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P4133": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3326": { propertyTypes: "—", greentownEquityRatio: 70 },
  "P3671": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3560": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3294": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: null },
  "P3361": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: null },
  "P3457": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3670": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3652": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 99.66 },
  "P3777": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3355": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3855": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3488": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3463": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3558": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 80 },
  "P3538": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3522": { propertyTypes: "车位储藏室", greentownEquityRatio: null },
  "P3647": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P4143": { propertyTypes: "住宅", greentownEquityRatio: null },
  "P3491": { propertyTypes: "住宅 / 商办 / 车位储藏室 / 加装包", greentownEquityRatio: null },
  "P3624": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 37 },
  "P3602": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3615": { propertyTypes: "—", greentownEquityRatio: 100 },
  "P3684": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: null },
  "P3298": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3448": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3335": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3677": { propertyTypes: "—", greentownEquityRatio: 60 },
  "P3510": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3380": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 48.87 },
  "P3477": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 39.72 },
  "P3899": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3384": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3552": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: null },
  "P3531": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 80 },
  "P3372": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 14 },
  "P3630": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 70 },
  "P3526": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3550": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3341": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 60.34546 },
  "P4099": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P4072": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3497": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: null },
  "P3302": { propertyTypes: "住宅 / 商办 / 车位储藏室 / 加装包", greentownEquityRatio: null },
  "P3760": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3759": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3484": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: null },
  "P3617": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P4067": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3472": { propertyTypes: "—", greentownEquityRatio: 0 },
  "P3657": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3828": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 100 },
  "P3496": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3903": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3582": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P4069": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3692": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 42.5319 },
  "P4129": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3826": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3367": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: null },
  "P3490": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3351": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3366": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: null },
  "P3313": { propertyTypes: "商办 / 车位储藏室", greentownEquityRatio: null },
  "P3734": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3634": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P4057": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3887": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3738": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P4068": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3827": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3633": { propertyTypes: "—", greentownEquityRatio: 20 },
  "P3373": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3319": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3702": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3603": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 32.64 },
  "P3569": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3407": { propertyTypes: "—", greentownEquityRatio: 60 },
  "P3649": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 100 },
  "P3606": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3445": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3656": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 86.82 },
  "P3431": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 32.89 },
  "P3309": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3440": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 29.69856 },
  "P3453": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 29.51 },
  "P3345": { propertyTypes: "住宅 / 商办", greentownEquityRatio: null },
  "P3523": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3701": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3901": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3520": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3444": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3866": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P4079": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P4089": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3402": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3519": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3674": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P4084": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3562": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: 74.65 },
  "P4058": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3385": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P4085": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3438": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3381": { propertyTypes: "—", greentownEquityRatio: null },
  "P3640": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: 77.07 },
  "P3425": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P3323": { propertyTypes: "住宅 / 商办 / 车位储藏室", greentownEquityRatio: null },
  "P4083": { propertyTypes: "住宅 / 车位储藏室", greentownEquityRatio: null },
  "P3506": { propertyTypes: "—", greentownEquityRatio: null },
};
